org: aryans1319
app: dailype-backend
service: dailype-backend
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9

functions:
  create_user:
    handler: handler.create_user
    events:
      - httpApi:
          path: /create_user
          method: post

resources:
  Resources:
    UsersDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: UsersTable
        AttributeDefinitions:
          - AttributeName: user_id
            AttributeType: S
        KeySchema:
          - AttributeName: user_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
