org: aryans1319
app: dailype-backend
service: dailype-backend
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9

functions:
  create_user:
    handler: handler.create_user
    events:
      - httpApi:
          path: /create_user
          method: post

  get_user:
    handler: handler.get_users
    events:
      - httpApi:
          path: /get_users
          method: get
          
  delete_user:
    handler: handler.delete_user
    events:
      - http:
          path: delete_user
          method: delete

  update_user:
    handler: handler.update_user
    events:
      - http:
          path: update_user
          method: put                

resources:
  Resources:
    UsersDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: UsersTable
        AttributeDefinitions:
          - AttributeName: user_id
            AttributeType: S
        KeySchema:
          - AttributeName: user_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
